#Page Mes Fichiers
#Menu
Link_Documents = "linkText:Documents"
Link_TousLesDocuments = "LinkText:Tous les documents"
ModifiésParMoiLink = "LinkText:Modifiés par moi"
ModifiésParDautresLink = "LinkText:Modifiés par d'autres"
RecemmentModifiesLink = "LinkText:Récemment modifiés"
RecemmentAjoutesLink = "LinkText:Récemment ajoutés"
MesFavorisLink = "LinkText:Mes favoris"
MesfichiersLink = "linkText:Mes fichiers"
CatégoriesLink = "linkText:Catégories"
CategorieRacineLink = "id:ygtvlabelel3"
Tagslink = "linkText:Tags"

#Sous Rubrique Selectionner
Btn_Selectionner = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-fileSelect-button-button"
DocumentsSelection = "xpath://span[text()=\"Documents\"]"
DossiersSelection = "xpath://span[text()=\"Dossiers\"]"
ToutSelection = "xpath://span[text()=\"Tout\"]"
InverserLaSelection = "xpath://span[text()=\"Inverser la sélection\"]"
AucunSelection = "Xpath://span[text()=\"Aucun\"]"
Btn_Eléments_sélectionnés = "id=template_x002e_documentlist_v2_x002e_myfiles_x0023_default-selectedItems-button-button"
Lnk_Deplacer_vers = "xpath://a/span[@class='onActionMoveTo']"

##sous deplacer vers
Lnk_toute_les_sites = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-copyMoveTo-site-button"
Lnk_Seleccion_Site1 = "xpath://a/h4[contains(text(),'"
Lnk_Seleccion_Site2 = "')]"
Lts_Sites = "xpath://div[@class='site']/div/div/a"
#Lnk_ToutesSites = "xpath://span/button[contains(text(),'Tous les sites')]"
Btn_Deplacer = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-copyMoveTo-ok-button"

#Sous Rubrique Créer
CreerButton = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createContent-button-button"
DossierCreation = "xpath://span[text()=\"Dossier\"]"
PleinTexteCreation = "xpath://span[text()=\"Plein texte...\"]"
HTMLCreation = "xpath://span[text()=\"HTML...\"]"
XMLCreation = "xpath://span[text()=\"XML...\"]"
CreerUnDocumentAPartirDunModele = "xpath://span[text()=\"Créer un document à partir d'un modèle\"]"
ModeleDeFichier = "//span[text()=\"modeledefichier.dotx\"]"
CreerUnDossierAPartirDunModele = "xpath://span[text()=\"Créer un dossier à partir d'un modèle\"]"
SoftwareEngineeringProjectModel = "xpath://span[text()=\"Software Engineering Project\"]"
Txt_Nom_Fichier = "id:template_x002e_create-content_x002e_create-content_x0023_default_prop_cm_name"
Txt_Titre_Fichier = "id:template_x002e_create-content_x002e_create-content_x0023_default_prop_cm_title"
Txt_Description_Fichier = "id:template_x002e_create-content_x002e_create-content_x0023_default_prop_cm_description"
Btn_Creer_Fichier = "id:template_x002e_create-content_x002e_create-content_x0023_default-form-submit-button"
Link_Racine_Fichier1 = "xpath://div/h3[@class='filename']/span/a[contains(text(),'"
Link_Racine_Fichier2 = "')]"
##Gérer les aspects
Link_Gerer_Aspect = "xpath://div/a/span[contains(text(),'Gérer les aspects')]"
Btn_Ajouter_ApectPartie1 ="xpath://div/h4[text()='" 
Btn_Ajouter_ApectPartie2 = "[@class='addIcon']" 
Link_Racine_Aspect = "']"
Generique_ancestor_aspect = "']/ancestor::tr/td/div/a/span"
List_aspects_left = "xpath://div[@class='yui-dt-liner']/h4"
List_aspect_right = "id:template_x002e_document-actions_x002e_document-details_x0023_default-aspects-right"
Btn_AppliquerModifications = "id:template_x002e_document-actions_x002e_document-details_x0023_default-aspects-ok-button"
#Sous Rubrique Importer dans l'entrepôt
ImporterDansLentrepot = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-fileUpload-button"

TriButton = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-sortAscending-button-button"

#Menu de Tri
NomButton = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-sortField-button-button"
TopScrollbar = "className:hd topscrollbar topscrollbar_disabled"
NomSelection = "linkText:\"Nom\""
PopulariteSelection = "LinkText:\"Popularité\""
TitreSelection = "LinkText:\"Titre\""
DescriptionSelection = "LinkText:\"Description\""
CreeSelection = "LinkText:\"Créé\""
CreateurSelection = "Linktext:\"Créateur\""
ModifieSelection = "LinkText:\"Modifié\""
ModificateurSelection = "LinkText:\"Modificateur\""
TailleSelection = "LinkText:\"Taille\""
TypeMineSelection = "LinkText:\"Type MIME\""
TypeSelection = "LinkText:\"Type\""
BottomScrollbar = "className:ft bottomscrollbar bottomscrollbar_disabled"

#Menu option
OptionsButton = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-options-button-button"
CacherLesDossiers = "xpath://span[@class=\"hideFolders\"]"
CacherLeFilDariane = "xpath://span[@class=\"hidePath\"]"
FluxRss = "xpath://span[@class=\"rss\"]"
PleineFenetre = "xpath://span[@class=\"fullWindow\"]"
PleinEcran = "xpath://span[@class=\"fullScreen\"]"
VueSimplifiée = "xpath://span[@class=\"view simple\"]"
VueDetaillee = "xpath://span[@class=\"view detailed\"]"
AffichageGalerie = "xpath://span[@class=\"view gallery\"]"
AffichagePellicule = "xpath://span[@class=\"view filmstrip\"]"
AffichageTable = "xpath://span[@class=\"view table\"]"
AffichageAudio = "xpath://span[@class=\"view audio\"]"
AffichageMedia = "xpath://span[@class=\"view media_table\"]"

Lnk_Dossier_Cree= "linkText:"
Lnk_Checkbox = "xpath://div/h3/span/a[contains(text(),'"
Lnk_Checkbox1 ="')]//ancestor::td/preceding-sibling::td//div/input[@type='checkbox']"
##Menu Flottant action sur dossier/Fichier
TelechhargerSousFormeDeZip = "id:onActionFolderDownload"
AfficherLesDetails = "className=folder-view-details"
EditerLesPropriete = "id:onActionDetails"
Plus = "id:onActionShowMore"
CopieVers = "id:onActionCopyTo"
DeplacerVers = "id:onActionMoveTo"
GererLesRegles = "className:folder-manage-rules"
SupprimerLeDossier = "id:onActionDelete"
GererLesDroitsDacces = "className:document-manage-repo-permissions"
GererLesAspects = "id:onActionManageAspects"

##Modal nouveau dossier
Modal_Nouveau_Dossier = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder-dialog"
Txt_Nom = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder_prop_cm_name"
Txt_Titre = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder_prop_cm_title"
Txt_Description = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder_prop_cm_description"
Btn_Enregister = "id:template_x002e_documentlist_v2_x002e_myfiles_x0023_default-createFolder-form-submit-button"
Modal_Confirmation = "id:message_c"
Link_Element = "xpath://a[text()='ELEMENT']"